<?xml version="1.0"?>
<package format="3">
  <name>input</name>
  <version>0.0.0</version>
  <description>Sensor nodes for BFMC (IMU, GPS, sonar, semaphore)</description>
  <maintainer email="futuremobilitychallenge@bosch.com">BFMC</maintainer>
  <license>BSD-3</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>utils</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
